github:
  owner: getsentry
  repo: sentry-go
preReleaseCommand: ""
changelogPolicy: simple
targets:
  - name: github
    tagPrefix: v
  - name: registry
    type: sdk
    config:
      canonical: "github:getsentry/sentry-go"
