minVersion: '0.9.0'
github:
  owner: getsentry
  repo: sentry-go
preReleaseCommand: bash scripts/craft-pre-release.sh
changelogPolicy: simple
statusProvider:
  name: github
  config:
    contexts:
      - Travis CI - Branch
targets:
  - name: github
    includeNames: /none/
    tagPrefix: v
  - name: registry
    type: sdk
    config:
      canonical: "github:getsentry/sentry-go"
