linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - unconvert
    - unparam
run:
  skip-dirs:
    - echo
    - example/echo
issues:
  exclude:
    - "not declared by package utf8"
    - "unicode/utf8/utf8.go"
  exclude-rules:
    - path: _test\.go
      linters:
        - prealloc
    - path: errors_test\.go
      linters:
        - unused
