repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: 96221dc741cb30cc0136999083dc6bd0e2113000
  hooks:
    - id: go-build
    - id: go-fmt
    - id: go-imports
    - id: golangci-lint
    - id: no-go-testing
