sudo: false

language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

env:
  - GO111MODULE=on GOFLAGS=-mod=readonly

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.19.1/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.19.1

script:
  - golangci-lint run
  - go build
  - go test
  - go test -race

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/befe9810-9285-11e9-b01a-0a580a281808/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
