name: Test
on:
  push:
    branches:
      - master
      - release/**
  pull_request:
permissions:
  contents: read
defaults:
  run:
    shell: bash
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Module Mode
    runs-on: ${{ matrix.os }}-latest
    env:
      GO111MODULE: "on"
      GOFLAGS: "-mod=readonly"
      # The race detector adds considerable runtime overhead. To save time on
      # pull requests, only run this step for a single job in the matrix. For
      # all other workflow triggers (e.g., pushes to a release branch) run
      # this step for the whole matrix.
      RUN_RACE_TESTS: ${{ github.event_name != 'pull_request' || (matrix.go == '1.26' && matrix.os == 'ubuntu') }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: '**/go.sum'
      - name: Tidy
        run: make mod-tidy
        if: ${{ matrix.go == '1.26' }}
      - name: Build
        run: make build
      - name: Vet
        run: make vet
      - name: Test${{ env.RUN_RACE_TESTS == 'true' && ' (with race detection)' || '' }}
        run: |
          if [ "${{ matrix.os }}" = "ubuntu" ] && [ "${{ matrix.go }}" = "1.26" ]; then
            ${{ env.RUN_RACE_TESTS == 'true' && 'make test-race-coverage' || 'make test-coverage' }}
          else
            ${{ env.RUN_RACE_TESTS == 'true' && 'make test-race' || 'make test' }}
          fi
      - name: Upload coverage to Codecov
        if: ${{ matrix.os == 'ubuntu' && matrix.go == '1.26' }}
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # pin@v6.0.0
        with:
          directory: .coverage
          token: ${{ secrets.CODECOV_TOKEN }}
    timeout-minutes: 15
    strategy:
      matrix:
        go: ["1.26", "1.25"]
        os: [ubuntu, windows, macos]
      fail-fast: false
