name: Test
on:
  push:
    branches:
      - master
      - release/**
  pull_request:
permissions:
  contents: read
defaults:
  run:
    shell: bash
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Module Mode
    runs-on: ${{ matrix.os }}-latest
    env:
      GO111MODULE: "on"
      GOFLAGS: "-mod=readonly"
      # The race detector adds considerable runtime overhead. To save time on
      # pull requests, only run this step for a single job in the matrix. For
      # all other workflow triggers (e.g., pushes to a release branch) run
      # this step for the whole matrix.
      RUN_RACE_TESTS: ${{ github.event_name != 'pull_request' || (matrix.go == '1.26' && matrix.os == 'ubuntu') }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: "**/go.sum"
      - name: Tidy
        run: make mod-tidy
        if: ${{ matrix.go == '1.26' }}
      - name: Build
        run: make build
      - name: Vet
        run: make vet
      - name: Test${{ env.RUN_RACE_TESTS == 'true' && ' (with race detection)' || '' }}
        run: ${{ env.RUN_RACE_TESTS == 'true' && 'make test-race' || 'make test' }}
    timeout-minutes: 15
    strategy:
      matrix:
        go: ["1.26", "1.25"]
        os: [ubuntu, windows, macos]
      fail-fast: false
